package:
  name: pysor-dev
  version: {{ GIT_DESCRIBE_TAG+ '+' +GIT_BUILD_STR }}
source:
  path: ../..

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython >=0.22
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - pytest 
    - pytest-cov
  imports:
    - pysor

about:
  home: http://github.com/cwehmeyer/pysor
  license: GNU Public License v3+
  summary: "Solve Poisson's equation with successive over-relaxation"
